services:
  db:
    image: postgres:15
    container_name: postgres_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${NAME_USER}
      POSTGRES_PASSWORD: ${NAME_PASSWORD}
      POSTGRES_DB: ${NAME_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - app/.env
    restart: always
    networks:
      - franchise-networks

  app:
    build:
      context: app
    container_name: back-end
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - app/.env
    volumes:
      - media_data:/app/media
      - static_data:/app/staticfiles
    environment:
      RUNNING_IN_DOCKER: 'true'
      POSTGRES_USER: ${NAME_USER}
      POSTGRES_PASSWORD: ${NAME_PASSWORD}
      POSTGRES_DB: ${NAME_DB}
    restart: always
    networks:
      - cms-networks


  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./app/nginx.conf:/etc/nginx/nginx.conf
      - static_data:/static
      - media_data:/media
      - /etc/letsencrypt:/letsencrypt
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - app
      - client
    restart: always
    networks:
      - cms-networks


volumes:
  media_data:
  postgres_data:
  static_data:

networks:
  cms-networks:
