# Generated by Django 5.1.5 on 2025-03-17 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='description',
            field=models.TextField(default='\n    <a id="hero__promo" href="#"> 1winrupromo </a> \n    <p> и получите бонус </p>\n    <span id="hero__price"> до 50000 рублей </span> \n    <p> при регистрации.</p>\n    ', verbose_name='Текст куска заголовка'),
        ),
    ]
