# Generated by Django 5.1.5 on 2025-03-18 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_site_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='description',
            field=models.TextField(default='\n    <a id="hero__promo" href="#">1winrupromo</a> и&nbsp;получите бонус\n            <span id="hero__price">до&nbsp;50&nbsp;000 рублей</span> при\n            регистрации.\n    ', verbose_name='Текст куска заголовка'),
        ),
        migrations.AlterField(
            model_name='site',
            name='promo_code',
            field=models.CharField(blank=True, null=True, verbose_name='Промо код'),
        ),
    ]
