# Generated by Django 5.1.5 on 2025-03-19 18:34

import django.db.models.deletion
import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_site_description_alter_site_promo_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField()),
                ('status', models.CharField()),
                ('user', models.CharField()),
                ('password', models.CharField()),
                ('skip', models.CharField(blank=True, null=True)),
                ('Cf_email', models.CharField(blank=True, null=True)),
                ('Cf_key', models.CharField(blank=True, null=True)),
                ('Php_mode', models.CharField(blank=True, null=True)),
                ('Registrar_vendor', models.CharField(blank=True, null=True)),
                ('Registrar_username', models.CharField(blank=True, null=True)),
                ('Registrar_apLKey', models.CharField(blank=True, null=True)),
                ('create_data', models.DateTimeField(default=main.models.get_moscow_time)),
                ('update_data', models.DateTimeField(default=main.models.get_moscow_time)),
            ],
        ),
        migrations.AddField(
            model_name='site',
            name='create_data',
            field=models.DateTimeField(default=main.models.get_moscow_time),
        ),
        migrations.AddField(
            model_name='site',
            name='update_data',
            field=models.DateTimeField(default=main.models.get_moscow_time),
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField()),
                ('current_domain', models.CharField()),
                ('domain_mask', models.CharField()),
                ('status', models.CharField()),
                ('create_data', models.DateTimeField(default=main.models.get_moscow_time)),
                ('update_data', models.DateTimeField(default=main.models.get_moscow_time)),
                ('server', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='domain', to='main.server')),
            ],
        ),
    ]
