# Generated by Django 5.1.5 on 2025-03-19 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_server_site_create_data_site_update_data_domain'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='site',
            name='id_vebmaster',
        ),
        migrations.RemoveField(
            model_name='site',
            name='valuable_main_domain',
        ),
        migrations.AddField(
            model_name='site',
            name='server',
            field=models.ManyToManyField(related_name='site_server', to='main.server', verbose_name='Существующий владелец домена'),
        ),
        migrations.RemoveField(
            model_name='site',
            name='domain_name',
        ),
        migrations.AddField(
            model_name='site',
            name='domain_name',
            field=models.ManyToManyField(related_name='site_domain', to='main.domain'),
        ),
    ]
