# Generated by Django 5.1.5 on 2025-03-20 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_site_id_vebmaster_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domain',
            name='Username',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='description',
            field=models.TextField(default='\n     \'<p> Используйте промокод: <a id="hero__promo" href="#">1winrupromo</a> и&nbsp;получите бонус <strong id="hero__price">до&nbsp;50&nbsp;000 рублей</strong> при регистрации.</p>\'\n    ', verbose_name='Текст куска заголовка'),
        ),
        migrations.RemoveField(
            model_name='site',
            name='domain_name',
        ),
        migrations.AlterField(
            model_name='site',
            name='main_link',
            field=models.CharField(blank=True, null=True, verbose_name='Основная ссылка на продукт казика'),
        ),
        migrations.RemoveField(
            model_name='site',
            name='server',
        ),
        migrations.AddField(
            model_name='site',
            name='domain_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='site_domain', to='main.domain'),
        ),
        migrations.AddField(
            model_name='site',
            name='server',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='site_server', to='main.server', verbose_name='Существующий владелец домена'),
        ),
    ]
