# Generated by Django 5.1.5 on 2025-03-20 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_domain_username_alter_site_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='yandex_metrika',
            field=models.CharField(blank=True, null=True, verbose_name='Яндех Метрика'),
        ),
    ]
