# Generated by Django 5.1.5 on 2025-03-26 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_site_yandex_metrika'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='server',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='site_server', to='main.server'),
        ),
    ]
