# Generated by Django 5.1.5 on 2025-04-02 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_site_button_2_alter_site_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='site',
            name='photo_about_2',
        ),
        migrations.RemoveField(
            model_name='site',
            name='photo_1',
        ),
        migrations.RemoveField(
            model_name='site',
            name='photo_about_3',
        ),
        migrations.RemoveField(
            model_name='site',
            name='button_1',
        ),
        migrations.RemoveField(
            model_name='site',
            name='button_2',
        ),
        migrations.RemoveField(
            model_name='site',
            name='button_3',
        ),
        migrations.RemoveField(
            model_name='site',
            name='description_1',
        ),
        migrations.RemoveField(
            model_name='site',
            name='description_2',
        ),
        migrations.RemoveField(
            model_name='site',
            name='description_3',
        ),
        migrations.RemoveField(
            model_name='site',
            name='description_4',
        ),
        migrations.RemoveField(
            model_name='site',
            name='description_5',
        ),
        migrations.RemoveField(
            model_name='site',
            name='link_for_site_1',
        ),
        migrations.RemoveField(
            model_name='site',
            name='link_for_site_2',
        ),
        migrations.RemoveField(
            model_name='site',
            name='link_for_site_3',
        ),
        migrations.RemoveField(
            model_name='site',
            name='title_1',
        ),
        migrations.RemoveField(
            model_name='site',
            name='title_2',
        ),
        migrations.RemoveField(
            model_name='site',
            name='title_3',
        ),
        migrations.RemoveField(
            model_name='site',
            name='title_4',
        ),
        migrations.RemoveField(
            model_name='site',
            name='title_5',
        ),
        migrations.AddField(
            model_name='site',
            name='data_block',
            field=models.JSONField(blank=True, default=[{'btn_link': 'https://1wrefr.com/casino/list?open=register&sub1=clickid&sub2=dopid', 'btn_text': 'Перейти на 1WIN', 'descr': '<p>Добро пожаловать на официальный сайт 1win casino. В 1 вин тебе повезет, даже если ты не новичок! И то, что ты попал на сайт 1win — твоя первая и главная победа! Врывайся в мир игровых слотов, и пусть удача сопутствует тебе. Игорные заведения — не только способ приятного времяпрепровождения, но и вероятность прилично поднять. Крути колесо и принимай удачу в гости! Счастливый билетик уже ждёт тебя на казино 1вин!</p>', 'image': '', 'title': 'О компании'}], null=True, verbose_name='Блоки'),
        ),
        migrations.AddField(
            model_name='site',
            name='faq',
            field=models.JSONField(blank=True, default=[{'description': 'Ответ', 'title': 'Вопрос'}], null=True, verbose_name='Вопросы Ответы'),
        ),
        migrations.AddField(
            model_name='site',
            name='meta_teg',
            field=models.JSONField(blank=True, default=[{'content': '', 'name': ''}], null=True, verbose_name='Мета теги'),
        ),
        migrations.AlterField(
            model_name='site',
            name='link_for_site',
            field=models.CharField(blank=True, null=True, verbose_name='Сслыка на заголовок продукта'),
        ),
        migrations.AlterField(
            model_name='site',
            name='title',
            field=models.CharField(blank=True, default='\n    1WIN ВХОД НА ОФИЦИАЛЬНЫЙ САЙТ\n    ', null=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='yandex_metrika',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Яндех Метрика'),
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
