# Generated by Django 5.1.5 on 2025-04-02 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_site_description_alter_site_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='title_button',
            field=models.CharField(blank=True, default='\nПерейти на 1WIN\n    ', null=True, verbose_name='Текст заголовка кнопки'),
        ),
    ]
