# Generated by Django 5.1.5 on 2025-04-14 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_site_data_block_alter_site_faq_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='meta_teg',
            field=models.JSONField(blank=True, default=[{'content': '', 'id': ''}], null=True, verbose_name='Мета теги'),
        ),
    ]
