# Generated by Django 5.1.5 on 2025-04-22 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_domain_redirect_domain'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vebmaster',
        ),
        migrations.AddField(
            model_name='domain',
            name='vebmaster_id',
            field=models.CharField(blank=True, null=True, verbose_name='Вебмастер'),
        ),
        migrations.AddField(
            model_name='domain',
            name='yandex_metrika',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Яндех Метрика'),
        ),
    ]
