# Generated by Django 5.1.5 on 2025-04-24 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_delete_vebmaster_domain_vebmaster_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='faq',
            field=models.JSONField(blank=True, default=[{'description': 'Ответ', 'id': '1', 'title': 'Вопрос'}], null=True, verbose_name='Вопросы Ответы'),
        ),
    ]
