# Generated by Django 5.1.5 on 2025-05-22 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_categoryaccess_person_access'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='access',
            field=models.ManyToManyField(blank=True, null=True, related_name='person_access', to='main.categoryaccess', verbose_name='Доступы'),
        ),
    ]
